### ISSUE TITLE
Využití formuláře jako komponenty

### ISSUE THREAD

**Issue by sinacek** [opendata-mvcr/lkod#1]
Plánujeme využít formulář jako komponentu v rámci LKODu. Za tímto účelem bychom potřebovali upravit vstupní a výstupní rozhraní. Toto issue je zastřešující pro několik následujících. 

- [x] Formulář příjme data přes POST a předvyplní se #2
- [x] Formulář příjme argument `returnUrl` a pokud je vyplněn tak data z formuláře odešle jako JSON-LD na danou url POSTem #3 
- [x] možnost do formuláře poslat vlastní JSON, který se nezobrazí a jen se pak přepošle zpět #4
